import "./globals.css";
import localFont from 'next/font/local'
import Analytics from "@/components/Analytics";

export const metadata = {
  title: "Gamertag",
  description: "Generated by create next app",
};

export const protoMono = localFont({
  src: [
    {
      path: '../fonts/ProtoMono-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/ProtoMono-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/ProtoMono-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/ProtoMono-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-proto',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Analytics/>
      <body className={protoMono.className}>{children}</body>
    </html>
  );
}
